name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison flex make git curl \
            clang lld llvm \
            libssl-dev libelf-dev

      - name: Configure
        run: |
          make \
            O=out \
            ARCH=arm64 \
            CC=clang \
            LD=ld.lld \
            LLVM=1 \
            LLVM_IAS=1 \
            vendor/holi-qgki_defconfig

      - name: Build
        run: |
          make -j$(nproc) \
            O=out \
            ARCH=arm64 \
            CC=clang \
            LD=ld.lld \
            LLVM=1 \
            LLVM_IAS=1
