name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison flex \
            build-essential \
            libssl-dev \
            libelf-dev \
            python3

      - name: Prepare
        run: |
          make ARCH=arm64 vendor/holi-qgki_defconfig

      - name: Build kernel
        run: |
          make -j$(nproc) ARCH=arm64
